---
- hosts: docker-hosts
  tasks:
    - name: Pull Docker image
      docker_image:
        name: bubinomob/simpleapp
        source: pull

    - name: Stop running container (if exists)
      docker_container:
        name: myapp
        state: stopped
        force_kill: true
        image: bubinomob/simpleapp

    - name: Remove old container (if exists)
      docker_container:
        name: myapp
        state: absent

    - name: Start new container
      docker_container:
        name: myapp
        image: bubinomob/simpleapp
        state: started
        restart_policy: always
        ports:
          - "8081:8080"
